[parsa]
type = s3
provider = Other
access_key_id = yAVNCZD9pxBgGff0
secret_access_key = jKOXN8ZMIQeSZQ1qlQJhkqWgUNigW8lX
region = us-east-1
endpoint = https://c905687.parspack.net
force_path_style = true
no_check_bucket = true